spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_plus?serverTimezone=Asia/Shanghai
    username: root
    password: yuguangbao
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0